name: Create Release Tarball

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Package Project
        run: |
          cd /home/runner/work/libldacdec/
          tar -czf /home/runner/work/libldacdec/libldacdec-1.0.tar.gz libldacdec
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libldacdec-1.0.tar.gz
          path: /home/runner/work/libldacdec/libldacdec-1.0.tar.gz
          
      - name: Release "libldacdec tarball release"
        uses: softprops/action-gh-release@v1
        with:
         body: developed by @anonymix007
         tag_name: workflow_${{github.run_number}}
         name: Release ${{github.run_number}}
         files: |
            /home/runner/work/libldacdec/libldacdec-1.0.tar.gz
