name: Create Release Tarball

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Package Project
        run: tar -czf project-${GITHUB_REF_NAME}.tar.gz .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-${GITHUB_REF_NAME}.tar.gz
          path: project-${GITHUB_REF_NAME}.tar.gz
